"""London Stansted Airport (STN) destinations — April 2026."""

DESTINATIONS = {
    "STN": {
        "name": "London Stansted",
        "routes": {
            "AAR": "Aarhus",
            "ACE": "Lanzarote",
            "ADB": "Izmir",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "ALG": "Algiers",
            "AMM": "Amman",
            "AMS": "Amsterdam",
            "AOI": "Ancona",
            "ARN": "Stockholm",
            "ASR": "Kayseri",
            "ATH": "Athens",
            "AYT": "Antalya",
            "BCN": "Barcelona",
            "BDS": "Brindisi",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGY": "Milan Bergamo",
            "BIQ": "Biarritz",
            "BJV": "Bodrum",
            "BLQ": "Bologna",
            "BOJ": "Bourgas",
            "BRE": "Bremen",
            "BRQ": "Brno",
            "BSL": "Basel",
            "BTS": "Bratislava",
            "BUD": "Budapest",
            "BZG": "Bydgoszcz",
            "BZR": "Beziers",
            "CAG": "Cagliari",
            "CCF": "Carcassonne",
            "CDT": "Castellon",
            "CFU": "Corfu",
            "CGN": "Cologne Bonn",
            "CHQ": "Chania",
            "CIA": "Rome Ciampino",
            "CLJ": "Cluj-Napoca",
            "CMF": "Chambery",
            "CMN": "Casablanca",
            "CPH": "Copenhagen",
            "CTA": "Catania",
            "DBV": "Dubrovnik",
            "DLM": "Dalaman",
            "DUB": "Dublin",
            "DXB": "Dubai",
            "EDI": "Edinburgh",
            "EFL": "Kefalonia",
            "EIN": "Eindhoven",
            "ESB": "Ankara",
            "ESU": "Essaouira",
            "FAO": "Faro",
            "FCO": "Rome Fiumicino",
            "FEZ": "Fez",
            "FKB": "Karlsruhe",
            "FLR": "Florence",
            "FMM": "Memmingen",
            "FMO": "Munster",
            "FNC": "Funchal",
            "FRA": "Frankfurt",
            "FUE": "Fuerteventura",
            "GDN": "Gdansk",
            "GLA": "Glasgow",
            "GNB": "Grenoble",
            "GOA": "Genoa",
            "GOT": "Gothenburg",
            "GRO": "Girona",
            "GVA": "Geneva",
            "GZT": "Gaziantep",
            "HAM": "Hamburg",
            "HEL": "Helsinki",
            "HER": "Heraklion",
            "IBZ": "Ibiza",
            "INN": "Innsbruck",
            "IST": "Istanbul",
            "JSI": "Skiathos",
            "JTR": "Santorini",
            "KGS": "Kos",
            "KIR": "Kerry",
            "KIV": "Chisinau",
            "KLU": "Klagenfurt",
            "KLX": "Kalamata",
            "KRK": "Krakow",
            "KSC": "Kosice",
            "KTW": "Katowice",
            "KUN": "Kaunas",
            "LBC": "Lubeck",
            "LCA": "Larnaca",
            "LCJ": "Lodz",
            "LDE": "Lourdes",
            "LIG": "Limoges",
            "LIS": "Lisbon",
            "LNZ": "Linz",
            "LPA": "Gran Canaria",
            "LUX": "Luxembourg",
            "MAD": "Madrid",
            "MAH": "Menorca",
            "MLA": "Malta",
            "MRS": "Marseille",
            "MXP": "Milan Malpensa",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NCE": "Nice",
            "NOC": "Knock",
            "NQY": "Newquay",
            "NTE": "Nantes",
            "NUE": "Nuremberg",
            "NYO": "Stockholm Skavsta",
            "OLB": "Olbia",
            "OMR": "Oradea",
            "OPO": "Porto",
            "ORK": "Cork",
            "OSI": "Osijek",
            "OSL": "Oslo",
            "OSR": "Ostrava",
            "OTP": "Bucharest",
            "PDV": "Plovdiv",
            "PEG": "Perugia",
            "PFO": "Paphos",
            "PGF": "Perpignan",
            "PIS": "Poitiers",
            "PLQ": "Palanga",
            "PMI": "Palma",
            "PMO": "Palermo",
            "POZ": "Poznan",
            "PRG": "Prague",
            "PSA": "Pisa",
            "PSR": "Pescara",
            "PUY": "Pula",
            "PVK": "Preveza",
            "RBA": "Rabat",
            "REG": "Reggio Calabria",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RIX": "Riga",
            "RMI": "Rimini",
            "RMU": "Murcia",
            "RTM": "Rotterdam",
            "RVN": "Rovaniemi",
            "RZE": "Rzeszow",
            "SAW": "Istanbul Sabiha",
            "SCQ": "Santiago",
            "SDR": "Santander",
            "SJJ": "Sarajevo",
            "SKG": "Thessaloniki",
            "SNN": "Shannon",
            "SOF": "Sofia",
            "SPU": "Split",
            "SSH": "Sharm El Sheikh",
            "STR": "Stuttgart",
            "SUF": "Lamezia Terme",
            "SVQ": "Seville",
            "SZG": "Salzburg",
            "SZZ": "Szczecin",
            "TFS": "Tenerife South",
            "TGD": "Podgorica",
            "TIA": "Tirana",
            "TIV": "Tivat",
            "TLL": "Tallinn",
            "TLS": "Toulouse",
            "TLV": "Tel Aviv",
            "TNG": "Tangier",
            "TPS": "Trapani",
            "TRF": "Oslo Torp",
            "TRN": "Turin",
            "TRS": "Trieste",
            "TSF": "Venice Treviso",
            "TUF": "Tours",
            "VCE": "Venice Marco Polo",
            "VGO": "Vigo",
            "VIE": "Vienna",
            "VLC": "Valencia",
            "VNO": "Vilnius",
            "VRN": "Verona",
            "WAW": "Warsaw Chopin",
            "WMI": "Warsaw Modlin",
            "WRO": "Wroclaw",
            "XRY": "Jerez",
            "ZAD": "Zadar",
            "ZAG": "Zagreb",
            "ZAZ": "Zaragoza",
            "ZRH": "Zurich",
            "ZTH": "Zakynthos",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
